### ISSUE TITLE
Ed25519 PKCS#8

### ISSUE THREAD

**Issue by Cucumber007ice** [binance/asymmetric-key-generator#41]
Ed25519 PKCS#8

**Comment by Cucumber007ice** [comment]
Ed25519 PKCS#8

**Comment by Cucumber007ice** [comment]
Ed25519 PKCS#8

**Comment by 1SThierarhyGOD** [comment]
Can You make it clearer, wanna me to add Your account? It's not protected overr the needed lv just flawless, ude default@default
